
###ALL USERS

GET http://localhost:3000/users HTTP/1.1

###

GET http://localhost:3000/users/base HTTP/1.1

####
GET http://localhost:3000/users/admins HTTP/1.1

###
GET http://localhost:3000/users/2 HTTP/1.1